---
apiVersion: v1
kind: Service
metadata:
  name: firstservice
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: mystatefulset
    app: mydeployment
  ports:
    - port: 80
      targetPort: 80
